version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name finalwork-bucket000 --s3-location s3://finalwork-bucket000/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src